MediaLib.Api/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MediaLib.Api.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            ViewBag.Title = "Home Page";

            return View();
        }
    }
}

MediaLib.Api/Controllers/MusicController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MediaLib.Data.Models;

namespace MediaLib.Api.Controllers
{
    public class MusicController : Controller
    {
        public ActionResult Index()
        {
            var music = new Movie
            {
                Name = "Trailerpark"
            };

            return View(music);
        }
    }
}

MediaLib.Api/Views/Home/Index.cshtml
<div class="jumbotron">
    <h1>Mediathek</h1>
    <p class="lead">Mediathek zur Verwaltung von Medien.</p>
</div>
<div class="row">
    <div class="col-md-4">
        <h2>Filme</h2>
        <p>Sieh dir alle verfügbaren Filme an!</p>
        @Html.ActionLink("Gehe zu", "Index", "Movies", new { @class = "btn btn-dark" })
    </div>
    <div class="col-md-4">
        <h2>Musik</h2>
        <p>Sieh dir die gesamte Musiksammlung an!</p>
        @Html.ActionLink("Gehe zu", "Index", "Music", new { @class = "btn btn-dark" })
    </div>
    <div class="col-md-4">
        <h2>Anmeldung</h2>
        <p>Melde dich an oder registriere dich!</p>
        <p class="btn btn-dark" href="https://go.microsoft.com/fwlink/?LinkId=301872"></p>
    </div>
</div>